# -*- coding: utf-8 -*-
"""Code Alpha Task 1 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GXwqQU1KyRV1gh-MFLHC0SXvDBQqu9Fm
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier


df=pd.read_csv(r'/content/drive/MyDrive/Iris.csv')

print("Dataset preview:")
print(df.head())

print("\nDataset info:")
print(df.info())

print("\nStatistical Summary:")
print(df.describe())

print("\nUnique Species:")
print(df["Species"].unique())


if "Id" in df.columns:
    df = df.drop("Id", axis=1)



sns.pairplot(df, hue="Species")
plt.show()



numeric_df = df.select_dtypes(include=["float64", "int64"])

plt.figure(figsize=(7,5))
sns.heatmap(numeric_df.corr(), annot=True, cmap="Blues")
plt.title("Correlation Matrix")
plt.show()


X = df.drop("Species", axis=1)
y = df["Species"]

le = LabelEncoder()
y = le.fit_transform(y)


target_names = le.classes_.astype(str)



X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)



model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)



y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("\nModel Accuracy:", accuracy)


print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=target_names))


cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(5,4))
sns.heatmap(
    cm,
    annot=True,
    cmap="Greens",
    fmt="d",
    xticklabels=target_names,
    yticklabels=target_names
)
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()



feature_importances = pd.DataFrame({
    "Feature": X.columns,
    "Importance": model.feature_importances_
}).sort_values(by="Importance", ascending=False)

print("\nFeature Importances:")
print(feature_importances)

plt.figure(figsize=(6,4))
sns.barplot(x=feature_importances["Importance"], y=feature_importances["Feature"])
plt.title("Feature Importance")
plt.show()
